### ISSUE TITLE
Возможность выбора уже распакованной игры

### ISSUE THREAD

**Issue by shuvaev32167** [seedhartha/QuestPlayer#19]
Добрый день
Не хватает возможности выбора уже распакованной игры.
В версии плеера от MrBoboFace такая возможность была (выбиралась папка с играми).

Для объёмный игр (> гигабайта) удобнее распакововать на компьютере и переносить игру в папку на флешку

**Comment by seedhartha** [comment]
Сделано в рамках 9edc18dcc5aed7964ad20e52f5fa9043098722d5. Будет выпущено в составе релиза 2.1.5.
