### ISSUE TITLE
Увеличить порог срабатывания свайпа в бок

### ISSUE THREAD

**Issue by seedhartha** [seedhartha/QuestPlayer#26]
Сейчас свайп в бок слишком чувствительный - пролистывая описание, можно легко переключиться на другое окно. Необходимо увеличить порог срабатывания свайпа в бок.

**Comment by seedhartha** [comment]
Исправлено коммитом abcd8cf2b4cb7f893308ec6b05be1e574034c556.

**Comment by ibigfire** [comment]
This is still too easy to accidentally do, could we maybe have an option to disable swiping to change tabs?  Thank you.
