### ISSUE TITLE
Хранение игр в external storage

### ISSUE THREAD

**Issue by seedhartha** [seedhartha/QuestPlayer#27]
Сейчас при удалении приложения или при установке несовместимой версии, игры и сохранения будут потеряны. Необходимо рассмотреть вопрос об использовании external storage с целью хранения игр.

Скорее всего, с реализацией возникнут сложности на более новых версиях Android.

**Comment by shuvaev32167** [comment]
Могу ошибаться, но как понял, для этого надо обратно с File перейти на DocumentFile, в теории это даст так же возможнсть выбора папки для игр. Но боюсь, что это может повлиять на работу OPENQST и ADDQST (6b9c588387546fb97d4e0cdce9315fed83682150)

**Comment by seedhartha** [comment]
За неимением времени не буду заниматься этим вопросом. В общем то проблема не такая критичная. Обновлять приложение без потери игр и сохранений можно, сохраняться в external storage - тоже.
