### ISSUE TITLE
can't load game file

### ISSUE THREAD

**Issue by iceberg2271** [seedhartha/QuestPlayer#29]
when I load game file about family life ,error code 105 
can't load file
[game.zip](https://github.com/seedhartha/QuestPlayer/files/5757554/game.zip)

**Comment by seedhartha** [comment]
What is this file? It does not open in classic player and QGen either.

**Comment by seedhartha** [comment]
QuestPlayer only supports games that the classic player does. This file is an encoded version (AeroQSP?).
