### ISSUE TITLE
Game folder selection

### ISSUE THREAD

**Issue by VBPXKSMI** [seedhartha/QuestPlayer#31]
Hello, would it be possible to select where the game gets installed (the output directory)? As in if I wanted to install and launch it from the SDcard? 
I think previous versions had a setting that allowed this but it was erased at some point.
I am not sure if I am communicating this correctly, my issue is that my internal storage is pretty low so I am in need of using external memory cards.

Would write this in russian but my skills on it are pretty basic, sorry.
Спасибо!

**Comment by seedhartha** [comment]
Hej!

Removing SDcard installation was a conscious decision to improve compatibility among different Android versions and reduce code complexity.

As much as I'd like to help, I don't have the time to re-implement that functionality currently, but I may do so in the future.

**Comment by VBPXKSMI** [comment]
Thought so, guess  I will have to make do.
Thanks for the fast reply and for your efforts.
