### ISSUE TITLE
Поддержка игр с файлом игры в подпапке

### ISSUE THREAD

**Issue by seedhartha** [seedhartha/QuestPlayer#9]
У некоторых игр на полке файл игры находится в подпапке, например "Осколки бессмертия", "Пленник зеленых холмов", "13-ая школа" и "Алиса. Девочка со спичками". Сейчас в этом случае плеер не может найти игру.

**Comment by AlexandrKozlovskiy** [comment]
Обратите пожалуйста внимание на мой pull request #12. Там я добавил эту возможность.

**Comment by seedhartha** [comment]
Реализовано в 791f9531ab4529e77b1d4732dda7f00fc8179b1d.
